name: Deploy to Firebase Hosting on merge
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}   # allow manual “Run workflow” button

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ARTEMISSKYS_81C8D }}'
          channelId: live
          projectId: artemisskys-81c8d
